### PR TITLE
Replace regex expression

### PR DESCRIPTION
**Pull request by hscheewel**
Following https://stackoverflow.com/questions/12643009/regular-expression-for-floating-point-numbers

### CODE REVIEW

**Comment by hscheewel** [comment]
Hi @ernesst, Could you check if this can be merged?

**Comment by ernesst** [comment]
Sorry for the long time, I just find out my Nexus 5 to test it. 

The rules works nicely on lattitude and accuracy but not longitude. I'm wondering if it's because mine is negative ?
(This is only difference between lat and lon)

**Comment by hscheewel** [comment]
Could you check if this one works for you? The regex should now be able to match positive and negative floats. On my phone (with lon, lat being both positive) it works. I've also reverted the change regarding the accuracy measure. Since it can only be positive there is no need to adjust this..

Edit: Here are some tests that show how the regex differ. The `.\d+.\d+` matches the white space (**␣**) in front of floats, `-?\d+\.\d+` only matches the negative sign in case it exits:

| City | True Position (lon,lat) | `.\d+.\d+` | `-?\d+\.\d+` |Same result|
|:-:|-|-|-|-|
| Sydney | (-33.8481647, 150.7918922) | ("-33.8481647", "**␣**150.7918922") | ("-33.8481647", "150.7918922") |✗|
| Tokyo | (36.5742646, 138.9480222) | ("**␣**36.5742646", "**␣**138.9480222") | ("36.5742646", "138.9480222") |✗|
| Santiago | (-33.4727092, -70.7699139) | ("-33.4727092", "-70.7699139") | ("-33.4727092", "-70.7699139") |✓|
| Seattle | (47.6129432, -122.4821457) | ("**␣**47.6129432", "-122.4821457") | ("47.6129432", "-122.4821457") |✗|
| London | (51.5360744, -0.2662339) | ("**␣**51.5360744", "-0.2662339") | ("51.5360744", "-0.2662339") |✗|

**Comment by ernesst** [comment]
Thanks,
I will look at it.

**Comment by ernesst** [comment]
Thank you very much, it works well.
I'm in the middle of relocating to a new country, I finally got a job ! I'll try to push a new version within couple of weeks.

**Comment by hscheewel** [comment]
Thank you for merging. And congrats for the job!

**Pull request merged**
